extends Node

# Preload scenes in this singleton to avoid redundant loading errors
const banner_scene: PackedScene               = preload('res://models/hud/hud_banner.tscn')
const block_half_1_scene: PackedScene         = preload("res://models/block/block_half_1.tscn")
const block_half_2_scene: PackedScene         = preload("res://models/block/block_half_2.tscn")
const block_quart_scene_1a: PackedScene       = preload("res://models/block/block_quart_1a.tscn")
const block_quart_scene_1b: PackedScene       = preload("res://models/block/block_quart_1b.tscn")
const block_quart_scene_2a: PackedScene       = preload("res://models/block/block_quart_2a.tscn")
const block_quart_scene_2b: PackedScene       = preload("res://models/block/block_quart_2b.tscn")
const block_scene: PackedScene                = preload('res://models/block/block.tscn')
const explosion_scene: PackedScene            = preload("res://models/explosive/explosion.tscn")
const explosive_shatter_scene: PackedScene    = preload("res://models/explosive/shatter.tscn")
const explosive_splash_scene: PackedScene     = preload("res://models/explosive/splash.tscn")
const gem_scene: PackedScene                  = preload("res://models/gem/gem.tscn")
const goal_scene: PackedScene                 = preload('res://models/player/goal.tscn')
const item_empty_scene: PackedScene           = preload("res://models/hud/hud_inventory_item_empty.tscn")
const item_projectile_scene: PackedScene      = preload("res://models/hud/hud_inventory_item_projectile.tscn")
const laser_scene: PackedScene                = preload("res://models/laser/laser_beam_cluster.tscn")
const pickup_projectile_scene: PackedScene    = preload("res://models/pickup/pickup_projectile.tscn")
const projectile_explosive_scene: PackedScene = preload("res://models/explosive/projectile_explosive.tscn")
const score_scene: PackedScene                = preload('res://models/hud/hud_score.tscn')
const ship_scene: PackedScene                 = preload('res://models/player/ship.tscn')
