extends Node

const block_collides_with_block = preload("res://assets/sound/block_collides_with_block.wav")
const block_collides_with_block_2 = preload("res://assets/sound/block_collides_with_block_2.wav")
const game_start = preload("res://assets/sound/game_start.wav")
const player_1_ready = preload("res://assets/sound/player_1_ready.wav")
const player_2_ready = preload("res://assets/sound/player_2_ready.wav")
const player_collects_gem = preload("res://assets/sound/player_collects_gem.wav")
const player_collects_gem_double = preload("res://assets/sound/player_collects_gem_double.wav")
const player_unready = preload("res://assets/sound/player_unready.wav")
const projectile_fail = preload("res://assets/sound/projectile_fail.wav")
const projectile_fire = preload("res://assets/sound/projectile_fire.wav")
const projectile_impact = preload("res://assets/sound/projectile_impact.wav")
const ship_accelerates = preload("res://assets/sound/ship_accelerates.wav")
const ship_accelerates_2 = preload("res://assets/sound/ship_accelerates_2.wav")
const ship_collides_with_block = preload("res://assets/sound/ship_collides_with_block.wav")
const ship_collides_with_block_2 = preload("res://assets/sound/ship_collides_with_block_2.wav")
const ship_drifts = preload("res://assets/sound/ship_drifts.wav")
const ship_drifts_2 = preload("res://assets/sound/ship_drifts_2.wav")
const ship_is_disabled = preload("res://assets/sound/ship_is_disabled.wav")
